### ISSUE TITLE
[WIP]--Windows paths “pd/bin” and “pd/src”

### ISSUE THREAD

**Issue by Lucarda** [pure-data/pd-lib-builder#39]
This data comes from various `make allvars`:

Showing what `"$(PROGRAMFILES)/pd/bin")` and `"$(PROGRAMFILES)/pd/src")` get:

# Msys1 (win8.1)

```
Lucarda@T410 /c/KatjaV/rawCfiles
$ make allvars
ls: C:\Program Files (x86)/pd/bin: No such file or directory
ls: C:\Program Files (x86)/pd/src: No such file or directory
```
...
```
variable (environment) PROGRAMDATA = C:\ProgramData
variable (environment) PROGRAMFILES = C:\Program Files (x86)
variable (environment) PROGRAMFILES(X86) = C:\Program Files (x86)
variable (environment) PROGRAMW6432 = C:\Program Files
```

# Msys2 (win8.1)

```
Lucarda@T410 MINGW32 /c/KatjaV/rawCfiles
$ make allvars
ls: cannot access 'C:\Program Files/pd/bin': No such file or directory
ls: cannot access 'C:\Program Files/pd/src': No such file or directory
```
.....
```
variable (environment) PROGRAMFILES = C:\Program Files
variable (environment) ProgramData = C:\ProgramData
variable (environment) ProgramFiles(x86) = C:\Program Files (x86)
variable (environment) ProgramW6432 = C:\Program Files
```

# Msys2 (win10)

```
Lucarda@win10exthd MINGW32 /g/win10onexthd/KatjaV/rawCfiles
$ make allvars
ls: cannot access 'C:\Program Files/pd/bin': No such file or directory
ls: cannot access 'C:\Program Files/pd/src': No such file or directory
```
....
```
variable (environment) PROGRAMFILES = C:\Program Files
variable (environment) ProgramData = C:\ProgramData
variable (environment) ProgramFiles(x86) = C:\Program Files (x86)
variable (environment) ProgramW6432 = C:\Program Files
```

# Msys2 (win10) 
```
Lucarda@win10exthd MINGW64 /g/win10onexthd/KatjaV/rawCfiles
$ make allvars
ls: cannot access 'C:\Program Files/pd/bin': No such file or directory
ls: cannot access 'C:\Program Files/pd/src': No such file or directory
```
...
```
variable (environment) PROGRAMFILES = C:\Program Files
variable (environment) ProgramData = C:\ProgramData
variable (environment) ProgramFiles(x86) = C:\Program Files (x86)
variable (environment) ProgramW6432 = C:\Program Files
```

Here some usefull information. The nsi-installer script:

https://github.com/pure-data/pure-data/blob/master/msw/build-nsi.sh

**Comment by katjav** [comment]
Summarizing above results, we have this issue (correct me if wrong): 

Pdlibbuilder assumes that Pd is installed in `$(PROGRAMFILES)/pd`. But for 32 bit Pd on 64 bit Windows, pdlibbuilder should search with `$(ProgramFiles(x86))/pd` instead. (path issue 1)

There is at least one more issue with paths for Windows builds. User variables `PDBINDIR`, `PDINCLUDEDIR` and PDDIR (`$(PDDIR)/src` and `$(PDDIR)/bin`) should have precendence over defaults `pdbinpath` and `pdincludepath`, which seems to be not the case in some situations (see issue #34). (path issue 2)

To detect the condition for path issue 1 we can conveniently use the newly introduced variables `build.arch` and `target.arch` (pdlibbuilder v0.5.0). However, path finding in pdlibbuilder is already a kludge of conditionals, especially for Windows. Therefore my proposal is to clean up the kludge where possible.

To start with, we can get rid of PD_PATH. This variable was introduced for compatibility with the centralized build system of Pd-extended, Pd-L2ork and Purr Data. But Purr Data has `pd/src/pd.dll` rather than `pd/bin/pd.dll` so PD_PATH is of no use:

https://git.purrdata.net/jwilkes/purr-data/commit/8af42734ae562cec8217f98770ac16d15848a460 

Also if we can get user variable precedence to work as expected, conditional checks around pdincludepath and pdbinpath can be omitted (`ifndef pdbinpath` etc.).

**Comment by katjav** [comment]
Here's the snag (path issue 2): variables to store linker flags are evaluated before this:

`PDBINDIR ?= $(pdbinpath)`

I'll first repair this and from there we can add a fix for path issue 1. When ready for testing I'll push topic branch `windows-paths`.

**Comment by Lucarda** [comment]
> Pdlibbuilder assumes that Pd is installed in $(PROGRAMFILES)/pd. But for 32 bit Pd on 64 bit Windows, pdlibbuilder should search with $(ProgramFiles(x86))/pd instead. **(path issue 1)**


This is the default Pd path when using the installer (32-bit-pd) on Win8.1 & Win10 (both OSs 64bit):

![w8 1](https://user-images.githubusercontent.com/25239522/35350303-4486c0a4-011c-11e8-9c08-0768546c56a2.jpg)


We can assume **(path issue 1)** should be “C:\Program Files (x86)”. Later for testing I will create folders there not using the installer (i don’t want a real installation for many reasons).


For me `pdincludepath=` & `pdbinpath=` where(are)  the most useful vars when using `make`. I will do some tests with `PDDIR` **(path issue 2)**

>we can get rid of PD_PATH.

Sure, only based on what you are saying. : )

**Comment by katjav** [comment]
In order to fix path 'issue 2', we can move the following line (currently 642):

`PDBINDIR ?= $(pdbinpath)`

upward into the Windows path section after line 603, and further down replace `pdbinpath` with `PDBINDIR`. Since the path to binaries is only used on Windows, it is not needed outside those sections.

**Comment by Lucarda** [comment]
Can you do a PR and we test it?.

**Comment by Lucarda** [comment]
sorry a branch?

**Comment by Lucarda** [comment]
@katjav 

We must be aware that developes will have 2 Pds to to compile against. So i think that `make pdincludepath=path/to pdbinpath=path/to` will be the most used.


Auto finding the correct Pd is more an issue to `-dumpmachine` ?

**Comment by Lucarda** [comment]
Can we get which Pd to look for based on `$(target.arch)` ?

**Comment by katjav** [comment]
Test branch is up. With commit 7740128, `PDDIR` should be able to point to any 'portable' or installed Pd on Windows and automatically find the src and bin dir from there. It is a 'conveniene variable', saving time for regular users and saving headaches for incidental users. For a different layout (Purr Data for example) one could always define PDINCLUDEDIR and PDBINDIR separately.

The convenience variable, also _settable in the environment_, was introduced in a flurry of optimism (see issue #27). Any convenience (read 'not strictly required') variable will bite one day. Now that we want two different paths to Pd on Windows we have to reckon with the Convenience Variable as well. I've been puzzling how to do it elegantly, but so far nothing else but spaghetti ideas.

**Comment by Lucarda** [comment]
`PDDIR=my/path` works **OK** on Windows msys1/2(32-64) from branch: `windows-paths`

**Comment by katjav** [comment]
Putting together your infos, it seems that a simple approach like this could work for default paths with MSYS1 / MSYS2:

```
programfiles := $(if $(ProgramFiles(x86)), $(ProgramFiles(x86)), $(PROGRAMFILES))
pdbinpath := $(shell ls -d "$(programfiles)/Pd/bin")
pdincludepath := $(shell ls -d "$(programfiles)/Pd/src")
```

**Comment by katjav** [comment]
Could we use the MSYSTEM variable here (which @danomatika has already mentioned twice)? These default paths are only defined in the context of MSYS anyway. Something like:

```
  ifeq ($(MSYSTEM), mingw32)
    programfiles := $(ProgramFiles(x86))
  else
    programfiles := $(PROGRAMFILES)
  endif
  pdbinpath := $(shell ls -d "$(programfiles)/Pd/bin")
  pdincludepath := $(shell ls -d "$(programfiles)/Pd/src")
```

**Comment by Lucarda** [comment]
Did’t we already have something for that when `target.arch = i686` ?.

Our trouble is that we don’t know if Pd-32 is “hosted” on a 64bitOs (x) or a 32bitOs (z).

(x) is the most standard situation and the App is located: “C:\Program Files (x86)”
(z) is rare, we expect that no developer will use only a 32bit Os ----> “C:\Program Files”.
  
```
 ifeq ($(MSYSTEM), mingw32)
    programfiles := $(ProgramFiles(x86))
```

This also won’t tell if we are on (x) or (z)

But we can use it anyway. : -)

**Comment by Lucarda** [comment]
May be is time to say “Bye bye” to Msys1.

There are case-sensitive diff that are not compatible :

# Msys1:

```
ifeq ($(MSYSTEM), MINGW32)
programfiles := ${PROGRAMFILES(X86)}
else
programfiles := $(PROGRAMW6432)
endif
```


# Msys2:

```
ifeq ($(MSYSTEM), MINGW32)
programfiles := ${ProgramFiles(x86)}
else
programfiles := $(ProgramW6432)
endif
```



Note that for both “ProgramFiles(x86)” must be inside {curly-braces} and MINGW32 must be upper-case.
Also note the "$(ProgramW6432)".

**Comment by Lucarda** [comment]
However and also dropping Msys1 heres something useful:

```
ifeq ($(MINGW_CHOST), i686-w64-mingw32)
programfiles := ${ProgramFiles(x86)}
else
programfiles := $(PROGRAMFILES)
endif
pdbinpath := $(shell ls -d "$(programfiles)/Pd/bin")
pdincludepath := $(shell ls -d "$(programfiles)/Pd/src")
```

“i686-w64-mingw32“ will only be the case for 64bitOS compiling for 32bit

**Comment by katjav** [comment]
> Did’t we already have something for that when target.arch = i686 ?.
> 
> Our trouble is that we don’t know if Pd-32 is “hosted” on a 64bitOs (x) or a 32bitOs (z).

Let's summarize `target.arch` and default locations per Msys environment. Values for `target.arch`:

- Msys1: mingw32
- Msys2 / MINGW32: i686 (i%86 generalized)
- Msys2 / MINGW64: x86_64

And isn't it the case that these path variables point to correct default locations:

- Msys1: PROGRAMFILES
- Msys2 / MINGW32: ProgramFiles(x86)
- Msys2 / MINGW64: PROGRAMFILES

Then we could use `ProgramFiles(x86)` when `target.arch` is `i%86` and `PROGRAMFILES` otherwise?

**Comment by katjav** [comment]
@Lucarda, can you explain why curly braces are required for `ProgramFiles(x86)`? According to GNU make docs parentheses and braces are equivalent when referencing variables in a makefile:

https://www.gnu.org/software/make/manual/html_node/Reference.html#Reference

**Comment by umlaeute** [comment]
i question the notion that a "32bit Windows installation" is rarely found as a development machine.
we shouldn't assume too much about the OS used (it's pretty easy to install msys2 once you found that msys1 is not enough; however, it's pretty complicated to crossgrade your 32bit OS to a 64bit OS without losing data).

also i find this upper/lowercasing very strange, since these are actually environment variables exported by Windows, and afaik envvars in windows are not case-sensitive. it's probably a problem of `make`

**Comment by katjav** [comment]
Just to put the importance of default Windows paths into perspective. Developers, maintainers and deken package distributors often build against 'portable' Pd directories so they can select a specific Pd version on a build machine of choice. With the fix of commit 7740128 path variable PDDIR can be used for such cases (I'm happy about that). Default paths are useful for incidental (re)compilation without setting up an explicit build environment. In particular for incidental users it is discourageing when things don't work when you just type 'make'. Even when this is a relatively rare use case, making this work correctly could get Windows users more involved with development and maintenance of Pd libs.

**Comment by katjav** [comment]
> Then we could use `ProgramFiles(x86)` when `target.arch is i%86` and `PROGRAMFILES` otherwise?

This is probably another one in my series of stupid ideas, based on the listings at the top of this issue and my lack of knowledge about Msys shells otherwise. Is it the case that all Msys environments can work on both architectures? If so, values from Msys environment can not be decisive on their own and the build machine's architecture should be taken into account.

Commands `uname -m` and `gcc -dumpmachine` do not necessarily give the same architecture even when bitness is the same. Sure this can be resolved somehow but that is the spaghetti I wanted to avoid if possible.

**Comment by katjav** [comment]
Or maybe Msys1 can work on Windows 64 bit but not compile for Windows 64 bit? Can we use something like:

```
mingw.cross := $(findstring i686-w64-mingw32, $(MINGW_CHOST))
ifdef mingw.cross
  programfiles := $(ProgramFiles(x86))
else
  programfiles := $(PROGRAMFILES)
endif
pdbinpath := $(shell ls -d "$(programfiles)/Pd/bin")
pdincludepath := $(shell ls -d "$(programfiles)/Pd/src")
```

This way Msys1 would still be supported since `$(findstring i686-w64-mingw32, $(MINGW_CHOST))` evaluates to an empty string if `MINGW_CHOST` is not defined, and $(PROGRAMFILES) is equivalent to PROGRAMFILES(X86) for Msys1, right?

**Comment by katjav** [comment]
Or:
 
```
mingw.cross := $(filter i%86-w64-w32, $(MINGW_CHOST))
programfiles := $(if $(mingw.cross), $(ProgramFiles(x86)), $(PROGRAMFILES))) 
pdbinpath := $(shell ls -d "$(programfiles)/Pd/bin")
pdincludepath := $(shell ls -d "$(programfiles)/Pd/src")
```

**Comment by katjav** [comment]
Related to the current topic, I wonder what happens if people (try) use a mingw shell rather than msys? The infos here seem to suggest that mingw shell is to be preferred when building native software for Windows, rather than building mingw tools:

https://github.com/msys2/msys2/wiki/MSYS2-introduction

When using mingw shell, will this have consequences for the value of variable `MINGW_CHOST` or the output from command `gcc -dumpmachine`? Or do these originate from mingw subsystems anyway?

**Comment by Lucarda** [comment]
Summarizing a couple of things:

# The Msys 1- 2 being incompatible:

The “environment variables” are case sensitive and incompatible. So we don't get them when we ask for them because they have to be spelled different. I also tested asking for both but this confuses Msys2:

```
programfiles := ${ProgramFiles(x86)}
programfiles := ${PROGRAMFILES(X86)} ### for msys1
```


“environment variables” reported by Msys2 (we drop Msys1 here) are useful if the user is on a non-english OS. For the Spanish one **${ProgramFiles(x86)}** would return **“C:\Archivos de Programa (x86)”**. I believe this is the “Sane” way to get those variables, also is most likely that Pd is installed in that non-english path.

# The curly-braces.

If I do : `programfiles := $(ProgramFiles(x86))` I get:

```
ls: cannot access ')/Pd/bin': No such file or directory
ls: cannot access ')/Pd/src': No such file or directory
```


>Related to the current topic, I wonder what happens if people (try) use a mingw shell rather than msys? 

All my tests where done on mingw shell. When compiling for 32 I use the mingw32 shell and for 64 the mingw64 shell.

> Or maybe Msys1 can work on Windows 64 bit but not compile for Windows 64 bit? 

This is correct. All 32 bit Apps work on 64bit winOS.  Msys1 use only an mingw32 so it only produce 32bit binaries.

**Comment by umlaeute** [comment]
to add confusion to the puzzle, i found a [superuser question](https://superuser.com/questions/1257692) which i translate to:

- on W32 (a pure 32bit Windows installation) we have 
  - `%ProgramFiles%` (usually `C:\Program Files\`) which is (obviously) for **32bit** applications
- on W64 (a 64bit Windows installations) we have
   - `%ProgramFiles%` `(still `C:\Program Files\`) for **64bit** applications
   - and `%ProgramFiles(x64)%` (usually `C:\Program Files (x86)\`) for **32bit** applications
- for WoW64 (the 32bit shim on W64) - that is any 32bit programm running on W64 - we have
   - `%ProgramFiles%` (resolving to `C:\Program Files (x86)\`)

**Comment by Lucarda** [comment]
As I posted above this is the “we all happy” answer:


Msys1 unsupported, all paths handled correctly with Msys2:

```
ifeq ($(MINGW_CHOST), i686-w64-mingw32)
programfiles := ${ProgramFiles(x86)}
else
programfiles := $(PROGRAMFILES)
endif
pdbinpath := $(shell ls -d "$(programfiles)/Pd/bin")
pdincludepath := $(shell ls -d "$(programfiles)/Pd/src")
```


“i686-w64-mingw32“ will only be the case for 64bitOS with a 32bit Pd compiling for 32bit

**Comment by Lucarda** [comment]
Here is what we get with:  `$(info $(MINGW_CHOST))`


# Win64bit

**mingw32 shell:**
`i686-w64-mingw32`

**mingw64 shell:**
`x86_64-w64-mingw32`

# Win32bit

**mingw32 shell (untested but expected)**
`i686-w32-mingw32`
or
`i686-pc-mingw32`

**Comment by katjav** [comment]
Curly braces thing is explained here:

https://stackoverflow.com/questions/35064793/how-to-use-environment-varialbe-programfilesx86-in-a-gnu-makefile

Parentheses in the variable name seem to be the culprit. This is an exceptional case where conventions of environment variables names are not followed (also with the lower case characters). Anyway good to know what causes this behaviour.

**Comment by katjav** [comment]
One question about your “we are all happy” solution, @Lucarda. If the following conditional check resolves to false:

`ifeq ($(MINGW_CHOST), i686-w64-mingw32)`

path $(PROGRAMFILES) will be used. According to your overview, Msys1 defines the following variables (on 64 bit Windows I assume):

```
variable (environment) PROGRAMDATA = C:\ProgramData
variable (environment) PROGRAMFILES = C:\Program Files (x86)
variable (environment) PROGRAMFILES(X86) = C:\Program Files (x86)
variable (environment) PROGRAMW6432 = C:\Program Files
```

So PROGRAMFILES is a synonym for PROGRAMFILES(X86) here, pointing to the path for 32 bit binaries, right? And for 32 bit Windows there is no other than PROGRAMFILES. Then why does your proposed formulation not support Msys1? I just want to understand before comitting.

**Comment by Lucarda** [comment]
Because when

`ifeq ($(MINGW_CHOST), i686-w64-mingw32)`

resolves **true** Msys2 can't handle the uppercase variable `(environment) PROGRAMFILES(X86) = C:\Program Files (x86)`

So is really about when condition is **true** when we have the incompatibility.

**Comment by katjav** [comment]
But we need no uppercase $(PROGRAMFILES(X86)) in the makefile to support Msys1, if $(PROGAMFILES) is equivalent?

**Comment by katjav** [comment]
Commit 1bcf78f implements "all happy".

**Comment by katjav** [comment]
What gives Msys1 with  $(info $(MINGW_CHOST))?

**Comment by Lucarda** [comment]
Good.

I'm having trouble with:

> But we need no uppercase $(PROGRAMFILES(X86)) in the makefile to support Msys1, if $(PROGAMFILES) is equivalent? 

As `MINGW_CHOST` does not work on **Msys1**. All incompatibility reports were done when we used `(MSYSTEM)`
which does not tell which is the “host” OS. That's why I come to  `MINGW_CHOST`

We can put the thing on standby if we want Msys1. But we all agreed to drop it if ....

: )

**Comment by Lucarda** [comment]
I think if we go back and use `(MSYSTEM)` we will find the incompatibilty of variable `$(PROGRAMFILES(X86))` and we will have to drop **Msys1** anyway. We are better with “all happy”

**Comment by katjav** [comment]
What means '`MINGW_CHOST` doesn't work on `Msys1`'? Doesn't exist or gives unuseful output?

What I'm trying to say is: if variable MINGW_CHOST doesn't exist for Msys1, make will evaluate this as an empty string. Meaning that

`ifeq ($(MINGW_CHOST), i686-w64-mingw32)`

will always evaluate to false for Msys1, and variable $(PROGRAMFILES) will always be used for Msys1. And since that points to `C:\Program Files (x86)` on Windows 64 bit and to `C:\Program Files`. So Msys1 would still be supported in that case, even when the fix targets Msys2 only.

**Comment by Lucarda** [comment]
Exactly.

Here you can inspect `make allvars` on Msys1 & 2 --> (64bit OS --32 and 64 mingw)

[all-happy-allvars-reports.zip](https://github.com/pure-data/pd-lib-builder/files/1669575/all-happy-allvars-reports.zip)


I have no 32bit OS to test.

Note: As a side effect Msys1 gets the correct path when we are on a 64bit OS. Not sure what will happen on a 32bit OS.

**Comment by katjav** [comment]
Thanks, looks good. Msys1 on 32 bit will also use $(PROGRAMFILES). So all Msys / Mingw environments should be covered with this. Theoretically.

**Comment by Lucarda** [comment]
> Theoretically. 

Apparently yes : - )

“All Happy”. : - )

**Comment by katjav** [comment]
I've pushed a few 'finishing touch' commits to branch `windows-paths` (fe45bcb being the latest, getting rid of error messages when Pd isn't found on default paths).

A friend was so kind to let me install Pd and Msys2 on his Windows 64 system so I could test a 'cross architecture' build with the new default paths. All went fine, except one thing: Pd wouldn't load the C++ object in my test set (it works fine on Linux). I haven't got the opportunity to figure out why but intuition says 'name mangling troubles'. I don't know how Pd (from Miller's distribution) was built. Anyway it is too early to say that we have another pdlibbuilder issue here. Also because most libs are C it need not prevent the release of another pdlibbuilder update.

**Comment by Lucarda** [comment]
> Pd and Msys2 on his Windows 64 system so I could test a 'cross architecture' build

> intuition says 'name mangling troubles'.

Wait. I'm just telling this because everyone who is not a "native windows" seems to get confused. All Pd people are away from windows, btw.

What do you mean with 'cross architecture'?

Did you use the Mingw32?

There shouldn't be any 'cross architecture'.

**Comment by Lucarda** [comment]
Tested fe45bcb.

All good. (Msys1 (32) - Msys2 (32-64))

Also checked the resulting binaries.

**Comment by katjav** [comment]
Thanks for testing @Lucarda.

Yes I built for 32 bit to test the `${ProgramFiles(x86)}` path that was added thanks to your investigations. Not being a "native windows" I've learned a lot through the collaboration on this topic. For future reference here is an explanation from Microsoft about the subsystem that emulates x86 architecture on 64 bit Windows:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa384249(v=vs.85).aspx

It is so seamlessly integrated that Windows users need not be aware of architecture differences.

**Comment by katjav** [comment]
Commit a1ad2e9 merges topic branch windows-paths into master. Summary of fixes:

- Variables `PDDIR` and `PDBINDIR` now have precedence over `pdbinpath` as they
 should.

- Default paths for 32 bit builds on 64 bit Windows are now implemented.

- Probing of `pdincludepath` and `pdbinpath` through command `ls` is removed to avoid
confusing error messages.

Unfortunately again the merge commit isn't visible via github commit history because it is an 'empty commit' done to document summary of fixes (could have been fast forward merge).  This is what annoys me most about github, 'flattened timeline'.

Closing this issue. Branch windows-paths will be deleted soon.
