### ISSUE TITLE
Make is not idempotent

### ISSUE THREAD

**Issue by residuum** [pure-data/pd-lib-builder#43]
As reported in https://github.com/residuum/PuRestJson/issues/46 calling `make` after a successful build gives an error message. I have traced the error to `declare-object-target` (https://github.com/pure-data/pd-lib-builder/blob/master/Makefile.pdlibbuilder#L968), but I am unsure on how to fix it, as I am unsure about the intention of this definition.

**Comment by umlaeute** [comment]
just another data point: i can call  `make` with the pd-lib-builder based [iemguts](https://git.iem.at/pd/iemguts) and [iemnet](https://git.iem.at/pd/iemguts) libraries multiple times just fine.

- iemguts is a simple one-C-file per object library
- iemnet uses a private shared library

**Comment by katjav** [comment]
It is true that Makefile.pdlibbuilder doesn't do exactly the same thing for a clean build compared to a rebuild. In the case that one or more build products are found, it checks implicit dependencies. For a clean build that is a waste of time (which can be considerable for large libraries build on slow machines). For several reasons, dependency checking is only done in memory, not written in a file. The code that does it starts at line you poin to:

```

# declare implicit prerequisites rule like 'object.o: header1.h header2.h ...'
# argument $1 is input source file(s)
# dir is explicitly added because option -MM strips it by default
define declare-object-target
$(dir $1)$(filter %.o: %.h, $(shell $(CPP) $(depcheck.flags) -MM $1)) $(MAKEFILE_LIST)
endef

# evaluate implicit prerequisite rules when rebuilding everything
ifdef must-build-everything
  $(if $(wildcard $(all.objects)), \
  $(info ++++ info: evaluating implicit prerequisites in lib $(lib.name).....) \
  $(foreach v, $(all.sources), $(eval $(call declare-object-target, $v))))
endif
```

When a clean build succeeds while a rebuild doesn't, it may be caused by a header file not found during dependency checking. For example, https://github.com/residuum/PuRestJson/blob/master/src/json-encode.h#L31, saying `#include <json-c/json.h>`. It seems that the source tree layout was changed.

**Comment by umlaeute** [comment]
> It seems that the source tree layout was changed.

i'm not sure what you mean by that.

here, i have these files installed by the system's `libjson-c-dev` package, and I am running both invocations of `make` immediately after each other - i doubt that anything (of relevance) has changed on the filesystem inbetween.

**Comment by katjav** [comment]
Sorry, I overlooked that it isn't a local dir. I should reproduce the issue to figure out, but no time today. Do you happen to know if this behavior is new, a regression possibly?

**Comment by umlaeute** [comment]
it was at least observed with both `0.4.4` and `0.5.0` (althout that is not a very "deep" history)

**Comment by umlaeute** [comment]
i did a quick check trying to build PuRestJSON with all *tagged* `pd-lib-builder` versions:

| version | state |
| ------- | ------- |
| `v0.5.0` | failed |
| `v0.4.4` | failed |
| `v0.4.3` | failed |
| `v0.4.2` | failed |
| `v0.4.1` | failed |
| `v0.4.0` | failed |
| `v0.3.1` | failed |
| `v0.3.0` | failed |
| `v0.2.8` | failed |
| `v0.2.7` | failed |
| `v0.2.6` | failed |
| `v0.2.5` | failed |
| `v0.2.4` | failed |
| `v0.2.3` | **OK** |
| `v0.2.2` | failed |
| `v0.2.1` | failed |
| `v0.2.0` | failed |
| `v0.1.0` | failed |
| `v0.0.2` | failed |
| `v0.0.1` | failed |
| `v0.0.0` | failed |

**Comment by residuum** [comment]
Maybe I am not really understanding it correctly, but why is there  a pattern `%.o: %.h` in `$(filter %.o: %.h, $(shell $(CPP) $(depcheck.flags) -MM $1))`? @umlaeute : Do the .h files in iemguts and iemlib have a corresponding .o file?

**Comment by umlaeute** [comment]
@residuum in *iemlib* this is true, but not in *iemguts*

**Comment by katjav** [comment]
@residuum, the issue is that source files are not defined with their extension in your makefile. It seems that it was ported from pd-extended's makefile template where class base names were sufficient. But for pdlibbuilder the file names are required, in this case:

`OBJECTS = rest.c oauth.c json-decode.c json-encode.c urlparams.c `

`lib.setup.sources = src/purest_json.c`

As it happens the omission of extension is only a problem when checking dependencies. When compiling the simple pattern targets are used:

```
%.o:: %.c
	$(call make-object-file,c)

%.o:: %.cc
	$(call make-object-file,cxx)

%.o:: %.cpp
	$(call make-object-file,cxx)
```

But for dependency checking the literal source file names are passed to the preprocessor. The output from CPP is filtered to get object targets (%.o:) and their implicit dependencies (%.h).

**Comment by residuum** [comment]
Yes, that was it.
